### ISSUE TITLE
Build machine doesn't execute tests

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#110]
Build machine doesn't execute tests

**Comment by odytrice** [comment]
I disabled it because the tests are integration tests based on the fact that they require a connection to the database and the build server can't connect to it and as such will always fail

**Comment by bizmonger** [comment]
Is there a difference between a build server and a test environment?
Ideally, we want a test environment to be a clone of production.

No?

**Comment by odytrice** [comment]
There is a significant difference between the build server/agent and Test Environment. The build server is in practice just a container that has only CPU available and probably the build tools like MSBuild/ .NET Framework and that's it. Its job is to pull your source, compile and run your tests statically after that it may or may not tear down everything. Some Build Servers can be made to talk over the network or to a database but its not a requirement.

A Test Environment on the other hand is a complete replica of production. It is a live running application with WebServer/Database etc. We could make our build server (VSTS) talk to it but I don't think AppVeyor can. 

It kinda defeats the whole goal of unit testing because the state of the DB determines whether a test will pass/fail. Or even worse make previously passing tests to fail
