### ISSUE TITLE
Spec 

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/Nikeza#29]
Here is what I think the first iteration of Nikeza should be:

**A simple blog engine.**

No front end code. Just a backend rendering HTML files. The backend would allow us to log in to an admin area where we would publish our content.

### Why?

I think that everything dwells on the backend. If we keep doing front end modules without having a backend/product to test with then we are wasting our time.

What do YOU think?

@bizmonger @odytrice @awright18 @marukami @BryanWilhite 

PS. I did a live stream vid about me thinking out loud about this but it came out so awful I deleted it. :)

**Comment by bizmonger** [comment]
I'm not convinced that this should be a blog engine.

I envisioned it being a tool for discovering a person's content across the web.

**Comment by BryanWilhite** [comment]
Discovering a person's content around the web is not a use case that I have considered. I am working on the dashboard concept that consolidates all of my content around the web via APIs (the most pervasive is traditional RSS). My work is based on the assumption that I already know where my content is. To actually help someone _discover_ where their stuff is...? Wow. I think Google is working on this...

As for the Blogging engine stuff, I am also working on this. My Blogging back-end I consider is very successful. It is a static JSON repository over Azure storage. My front end I consider a disaster (from a SEO perspective) because I went with Angular 1.x. So I am busy at work building a new pipeline for the front end (which is why @bizmonger's interest in Elm is also interesting to me).

**Comment by bizmonger** [comment]
Cool. So feel free to assign the YouTube and/or Wordpress integration task to yourself.

**Comment by BryanWilhite** [comment]
Not exactly a feeling of “freedom”... I will check out https://github.com/Lambda-Cartel/Nikeza/issues and see where I can be effective. I am not in a rush and take full responsibility for misunderstandings coming from that.

**Comment by bizmonger** [comment]
Closing.
UI prototype nearly complete.
